### ISSUE TITLE
Errror Generating *Uber.Jar

### ISSUE THREAD

**Issue by sameersoneja** [forcedotcom/wsc#107]
Getting Error while generating *Uber.jar. Doing it for the first time . Any pointers greatly appreciated. 
JDK 1.8 , Branch wsc-master 
Below is the outcome.. 

C:\SalesForce\EAI_\wsc-master>C:\SalesForce\EAI_\apache-maven-3.3.3\bin\mvn clea
n package -Dgpg.skip
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building force-wsc 35.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ force-wsc ---
[INFO] Deleting C:\SalesForce\EAI_\wsc-master\target
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ force-wsc ---
[INFO]
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ force-ws
c ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 20 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ force-wsc ---

[INFO] Compiling 118 source files to C:\SalesForce\EAI_\wsc-master\target\classe
s
[INFO]
[INFO] --- maven-resources-plugin:2.4.3:testResources (default-testResources) @
force-wsc ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ force
-wsc ---
[INFO] Compiling 9 source files to C:\SalesForce\EAI_\wsc-master\target\test-cla
sses
[INFO]
[INFO] --- maven-surefire-plugin:2.7.1:test (default-test) @ force-wsc ---
[INFO] Surefire report directory: C:\SalesForce\EAI_\wsc-master\target\surefire-
reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.sforce.async.CSVReaderTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.384 sec
Running com.sforce.ws.bind.XmlObjectTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.056 sec
Running com.sforce.ws.codegen.AggregateCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.153 sec <<< FA
ILURE!
Running com.sforce.ws.codegen.ComplexTypeCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.189 sec <<< FA
ILURE!
Running com.sforce.ws.codegen.ConnectionCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.183 sec <<< FA
ILURE!
Running com.sforce.ws.codegen.ConnectorCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.153 sec <<< FA
ILURE!
Running com.sforce.ws.codegen.SimpleTypeCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.159 sec <<< FA
ILURE!
Running com.sforce.ws.codegen.SObjectCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.163 sec <<< FA
ILURE!

Results :

Failed tests:
  testGenerateSObjectSource(com.sforce.ws.codegen.SObjectCodeGeneratorTest)

Tests run: 16, Failures: 6, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.848 s
[INFO] Finished at: 2015-09-03T21:01:21-05:00
[INFO] Final Memory: 21M/51M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
7.1:test (default-test) on project force-wsc: There are test failures.
[ERROR]
[ERROR] Please refer to C:\SalesForce\EAI_\wsc-master\target\surefire-reports fo
r the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

C:\SalesForce\EAI_\wsc-master>

****************************************************************

Here are details from one of the report files. 

-------------------------------------------------------------------------------
Test set: com.sforce.ws.codegen.AggregateCodeGeneratorTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.153 sec <<< FAILURE!
testGenerateSObjectSource(com.sforce.ws.codegen.AggregateCodeGeneratorTest)  Time elapsed: 0.128 sec  <<< FAILURE!
junit.framework.ComparisonFailure: null expected:</*[
 * Copyright (c) 2005-2013 salesforce.com, inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided
 * that the following conditions are met:
 *
 *    Redistributions of source code must retain the above copyright notice, this list of conditions and the
 *    following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright notice, this list of conditions and
 *    the following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 *    Neither the name of salesforce.com, inc. nor the names of its contributors may be used to endorse or
 *    promote products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package com.sforce.soap.enterprise.sobject;

import com.sforce.ws.bind.XmlObject;
import com.sforce.ws.bind.TypeMapper;
import com.sforce.ws.wsdl.Constants;
import com.sforce.ws.parser.XmlInputStream;
import com.sforce.ws.parser.XmlOutputStream;
import com.sforce.ws.ConnectionException;

import javax.xml.namespace.QName;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.IOException;

/**
 */
public class AggregateResult extends SObject {

    private XmlObject xmlObject = new XmlObject();

    /**
     * Constructor
     */
    public AggregateResult() {
    }

    public Object getField(String name) {
        return xmlObject.getField(name);
    }

    @Override
    public String getId() {
        return (String)xmlObject.getField("Id");
    }

    @Override
    public void setId(String id) {
        xmlObject.setField("Id", id);
    }

    @Override
    public void write(QName element, XmlOutputStream out, TypeMapper typeMapper) throws IOException {
        xmlObject.write(element, out, typeMapper);
    }

    @Override
    public void load(XmlInputStream in, TypeMapper typeMapper) throws IOException, ConnectionException {
        xmlObject.load(in, typeMapper);
    }
}]
> but was:</*[
 * Copyright (c) 2005-2013 salesforce.com, inc.
 * All rights reserved.
 *

**Comment by sudharsannr** [comment]
Same here. Any updates?

**Comment by sameersoneja** [comment]
Please ignore the failures in windows , using the switch depicted here.. 

http://mauricekremer.dscloud.me/force-com-generating-the-wsc-from-source/

That way you would be able to generate Jar and Proceed forard.

**Comment by diracz** [comment]
Closing the issue as @sameersoneja got the solution.
