### ISSUE TITLE
Winter'15 bug causes Summer'15 WSC api to fail

### ISSUE THREAD

**Issue by gsmtihfarmer** [forcedotcom/wsc#108]
See: https://developer.salesforce.com/forums/?state=id#!/feedtype=SINGLE_QUESTION_DETAIL&dc=APIs_and_Integration&criteria=OPENQUESTIONS&id=906F0000000BWxgIAG

Basically new SoapTypes introduced in the  Winter'15 API are bleeding into the Summer'15 API. The protocol 34 version of WSC throws a fatal exception when one of the new types is encountered.  A quick way to reproduced the bug is a describeObject() on SearchLayout.

Technically this is not a bug in WSC but code based on the protocol 34 version may stop working once Winter'15 goes GA (code already fails in the sandbox environment).

**Comment by gnguyen-sfdc** [comment]
Sorry for the delay. Thank you very much for notifying us. The fix was made available shortly afterwards. Closing this issue now.
