### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/sforce/ws/ConnectionException

### ISSUE THREAD

**Issue by prolayc** [forcedotcom/wsc#117]
I followed these steps to generate Partner.jar file -

1. I downloaded the Partner WSDL from the Sandbox and saved it as Partner.wsdl file in the local directory.

2. According to the latest resolved issue of this forum https://github.com/forcedotcom/wsc/issues/92, I downloaded the Uber JAR file from the location http://central.maven.org/maven2/com/force/api/force-wsc and the StringTemplate Jar from 
http://www.stringtemplate.org/

3. According to the http://sforcehacks.blogspot.in/2013/04/building-partnerjar-api-file.html, we require the latest Rhino library which I downloaded from http://mvnrepository.com/artifact/rhino/js. 

4. We also need the Tools.jar of the latest JDK. I included the Tools.jar path while generating the Partner.jar

I used these jar files and the wsdl file to generate Partner.jar -
A. force-wsc-35.2.5-uber.jar
B. js-1.7R2.jar
C. ST-4.0.8.jar
D. sandbox-partner.wsdl

The output as below screen shot
![image](https://cloud.githubusercontent.com/assets/5306583/11168075/9a6dc09c-8ba5-11e5-8815-a13c7e93aa86.png)

Then I complie the PartnerSamples.java to generate the class file. Please see the screen shot below.

![image](https://cloud.githubusercontent.com/assets/5306583/11168083/19f3bfc4-8ba6-11e5-8dd0-59e97740e4a2.png)

While running the Class file, I am getting the following error

![image](https://cloud.githubusercontent.com/assets/5306583/11168109/98656d70-8ba7-11e5-815a-08d68d94c807.png)

Please help me to reslve the issue.

Thanks in Advance.

**Comment by gnguyen-sfdc** [comment]
In the command prompt screenshot where you run "java PartnerSamples", it does not look like you have set the classpath, either by using -classpath or set CLASSPATH. Please use one of those, like you did in the previous commands, and see if that resolves the issue.

**Comment by prolayc** [comment]
@gnguyen-sfdc, Thank you for your response. I am really getting confused with the CLASSPATH setting. As you suggested I did the following. Please see the below scree shot.
![image](https://cloud.githubusercontent.com/assets/5306583/11189276/4c977aa0-8cb5-11e5-8af3-d9c7b40c4dd0.png)

I would like to point out that I am getting the following warning while generating the partner.jar
[WSC][wsdlc.main:71]Compiling to target 1.6...
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning

Is it causing the issue? I set the CLASSPATH as you suggested and I also removed the System CLASSPATH variable. According to the Oracle documentation Wildcard Classpath should be as follows -
CLASSPATH=C:\Program Files\Java\jdk1.8.0_66\lib\*;C:\Program Files\Java\jre1.8.0_66\lib\*;. *;

Please sugesst me what I am missing here.

**Comment by prolayc** [comment]
I also tried to run the Hello World java program and it ran without any issue.

**Comment by gnguyen-sfdc** [comment]
The warning when you generate the partner.jar is not an issue.

Classpaths are important to understand when running Java applications. I would suggest learning more, for example from here: https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html

In your particular case, you need a classpath that includes the partner JAR AND your current folder where you have PartnerSamples.class. Try "set CLASSPATH=.\*;." and then running your java command. That sets the classpath to all JARs in your current directory and all .class files in your current directory.

**Comment by prolayc** [comment]
It got resolved when I set the CLASSPATH as below

set CLASSPATH=.*;"C:\Program Files\Java\jdk1.8.0_66\lib\*";C:\Program Files\Java\jre1.8.0_66\lib\*";.\force-wsc-35.0.0.jar;.\partner.jar;

Thank you, @gnguyen-sfdc
