### ISSUE TITLE
Missing import packages com.sforce.ws.*

### ISSUE THREAD

**Issue by silverskyvicto** [forcedotcom/wsc#123]
Hi
When I Generated Java Stub Files (WSDL-Based APIs), I see that the above are missing.

```
import com.sforce.ws.ConnectionException;
import com.sforce.ws.ConnectorConfig;
import com.sforce.soap.enterprise.Connector;
import com.sforce.soap.enterprise.DeleteResult;
import com.sforce.soap.enterprise.EnterpriseConnection;
import com.sforce.soap.enterprise.Error;
import com.sforce.soap.enterprise.QueryResult;
import com.sforce.soap.enterprise.SaveResult;
import com.sforce.soap.enterprise.sobject.Account;
import com.sforce.soap.enterprise.sobject.Contact;
```

Package that has been generated is shown in the following image.
![existingpackage](https://cloud.githubusercontent.com/assets/3609003/11987920/e442a504-aa2a-11e5-99e0-8441767360c4.png)

I use following files.
- force-wsc-35.0.0.jar
- rhino1.7.7/js.jar
- ST-4.0.8.jar

I used wrong files? I want tell you what to do.

**Comment by gnguyen-sfdc** [comment]
Please refer to the intro page on WSC here: https://developer.salesforce.com/page/Introduction_to_the_Force.com_Web_Services_Connector and make sure you have followed all the steps.

**Comment by l-tamas** [comment]
@gnguyen-sfdc I'm experiencing the same issue. Trying to build the JAR for the Partner API with WSC 36.2.0. The operation is completed without errors, however the only available packages are:

- **com.sforce.soap.partner**
- **com.sforce.soap.partner.fault**
- **com.sforce.soap.partner.sobject**

Which means **com.sforce.ws** is missing, that makes the whole thing pretty unusable. Any hint would be highly appreciated.
