### ISSUE TITLE
Issue in using partnerconnection.update function WSC adapter

### ISSUE THREAD

**Issue by ozgit** [forcedotcom/wsc#136]
Hi All,

I am not sure if this is issue with WSC adapter. I posted below question on Salesforce developers site in hope to get some help.

I am facing issues using connection.update function. Below is Java code snippet I am using. This code snippet was built using reference available on https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sample_update_call.htm.
Issue is that if I pass single argument to connection.update function like connection.update(new SObject[] {updateItem }) it fails with below error 
***********************************************************************************************************
Error code: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY
Error message: ORG.TMnItem: execution of BeforeUpdate
caused by: System.QueryException: invalid ID field: null

(ORG)
***********************************************************************************************************

When I pass same SObject parameter two or more time to this function, the first time execution fails and it works fine for second object argument. Below is output when I passed same object parameter two times like connection.update function like connection.update(new SObject[] {updateItem, updateItem })
***********************************************************************************************************
Error code: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY
Error message: ORG.TMnItem: execution of BeforeUpdate
caused by: System.QueryException: invalid ID field: null

(ORG)

Item: 1
Contact with an ID of a3y290000004LZoAAM was updated.
***********************************************************************************************************

As shown in above message function failed to udpate on first object but it successfully updated record in second attempt. After this if I keep passing single object as input parameter the program works well. But if there is any change in program example, if I change updateItem.setField("ORG_Integration_Status__c", "Submitted") to updateItem.setField("ORG_Integration_Status__c", "Completed") the program starts failing again. So in order to make it succeed I need to pass same object multiple times to update function. This is a weired scenario I have come across in Java programming. Sometimes the function works fine and same function fails to work sometimes.

Below is code snippet:
    try 
    {
            String Temp_item = "a3y290000004LZoAAM";
            SObject updateItem = new SObject();
            updateItem.setType("ORG__MnItem__c");
            updateItem.setId(Temp_Item);
            updateItem.setField("ORG_Integration_Status__c", "Submitted");

            SaveResult[] saveResults = connection.update(new SObject[] {updateItem, updateItem });

            for (int j = 0; j < saveResults.length; j++) 
            {
                System.out.println("\nItem: " + j);
                if (saveResults[j].isSuccess()) 
                {
                    System.out.println("Contact with an ID of " + saveResults[j].getId() + " was updated.");
                } 
                else 
                {
                    for (int i = 0; i < saveResults[j].getErrors().length; i++) 
                    {
                        com.sforce.soap.partner.Error err = saveResults[j].getErrors()[i];
                        System.out.println("Errors were found on item " + j);
                        System.out.println("Error code: " + err.getStatusCode().toString());
                        System.out.println("Error message: " + err.getMessage());
                }
            }
        }
        } catch (ConnectionException e1) {
            e1.printStackTrace();
        }

    }

I appreciate any help on this. Thank you.

**Comment by ozgit** [comment]
Can someone please help..

**Comment by diracz** [comment]
My guess is that it's outside of the WSC, likely to be the org's setup. Did you have any trigger setup for this entity type which may lock the execution? Does upsert yield the same behavior?

**Comment by ozgit** [comment]
Thank you "diracz". Our SFDC development team made some changes in APIs and their dependencies. I am not SalesForce expert because of which I am not able to describe technically what they did but it resolved issue with UPDATE call. 
Thank you again for your response.
