### ISSUE TITLE
class XmlOutputStream made AutoCloseable fails compilation with Java 1.6

### ISSUE THREAD

**Issue by hyddeepak** [forcedotcom/wsc#146]
Hi

We are using Salesforce Bulk, (forcedotcom/wsc), for our application and are mandated to use Java 1.6 as our application supports Java 1.6. During the compilation of the code (37.0.3.zip) with Java 1.6 we see the error saying "cannot find symbol for "AutoCloseable" .

[ERROR] \Workspace\buildPartnerWSDL\buildWSCJava16\wsc-37.0.3\src\main\java\com\sforce\ws\parser\XmlOutputStream.java:[42,40] cannot find symbol
[ERROR] symbol: class AutoCloseable
[ERROR] public class XmlOutputStream implements AutoCloseable {
[ERROR] \Workspace\buildPartnerWSDL\buildWSCJava16\wsc-37.0.3\src\main\java\com\sforce\ws\parser\XmlOutputStream.java:[42,40] cannot find symbol
[ERROR] symbol: class AutoCloseable
[ERROR] public class XmlOutputStream implements AutoCloseable {
[ERROR] \Workspace\buildPartnerWSDL\buildWSCJava16\wsc-37.0.3\src\main\java\com\sforce\ws\parser\XmlOutputStream.java:[119,4] method does not override or

`public class XmlOutputStream implements AutoCloseable {
    private MXSerializer serializer = new MXSerializer();
    private OutputStream out;`

Well, as we understand that "AutoCloseable" was introduced for Java 1.7, and our requirement mandates us to use Java 1.6. In such a case then how do we proceed. 

Regds,
Deepak``

**Comment by reubencornel** [comment]
I'm sorry we cannot support multiple versions of java at this point. We talked about maintaining different branches for different versions of java but that makes maintaining this library difficult. The only way to get around this would be to fork it and remove auto closeable.
