### ISSUE TITLE
"mvn clean package" fails due to missing license header in SoapConnectionTest.java

### ISSUE THREAD

**Issue by thobach** [forcedotcom/wsc#148]
[INFO] Checking licenses...
[WARNING] Property 'strictChecking' is not enabled. Please consider adding <strictChecking>true</strictChecking> in your pom.xml file.
[WARNING] See http://code.google.com/p/maven-license-plugin/wiki/Configuration for more information.
[INFO] Missing header in: /Users/thobach/Downloads/wsc/wsc/src/test/java/com/sforce/ws/transport/SoapConnectionTest.java
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48.660 s
[INFO] Finished at: 2016-07-15T14:31:12+02:00
[INFO] Final Memory: 35M/493M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.mycila.maven-license-plugin:maven-license-plugin:1.8.0:check (default) on project force-wsc: Some files do not have the expected license header -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by diracz** [comment]
-Dlicense.skip=true should temporarily get you unblocked.

**Comment by reubencornel** [comment]
This should be fixed in #149

**Comment by caot** [comment]
`-Dlicense.skip` works
