### ISSUE TITLE
Using com.sforce.async.CSVReader gives the error 

### ISSUE THREAD

**Issue by hyddeepak** [forcedotcom/wsc#150]
Hi

This is the error seen while using "com.sforce.async.CSVReader" to extract more then 10,000 Records. when I call the "rdr.nextRecord()" method while trying to extract more then 10,000 records. Is this expected, and should I be keeping a count of the records before reading and process it when the record count is 10001 records

I am using "wsc-37.0.3"

_Exception in thread "main" com.sforce.async.CSVReader$CSVParseException: Exceeded number of records : 10002. Number of records should be less than or equal to 10001
	at com.sforce.async.CSVReader.checkRecordExceptions(CSVReader.java:157)
	at com.sforce.async.CSVReader.nextRecord(CSVReader.java:189)
	at BulkQuery.checkResults(BulkQuery.java:125)_

  ``

        for (String queryResult : queryResults) 
        { 
            CSVReader rdr = 
                new CSVReader(connection.getQueryResultStream(job.getId(), batchInfo.getId(), queryResult)); 
            List<String> resultHeader = rdr.nextRecord(); 
            int resultCols = resultHeader.size();            

            if(resultCols > 0)
            {
            	System.out.print(resultHeader.get(0)); // Print the first column Name          	
                for (int i = 1; i < resultCols; i++) 
                { 
                	System.out.print( "," + resultHeader.get(i)); 
                } 
                System.out.println(); 
                List<String> row; 
                while ((row = rdr.nextRecord()) != null)   // LINE 125 where the above mentioned error is thrown
                {   
                	System.out.print(row.get(0));// Print the first column data
                .......
                }
          }
        }

**Comment by amihaihalevy** [comment]
You cannot have more than 10,000 records per batch.
see:
https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_concepts_limits.htm

**Comment by reubencornel** [comment]
Yes, that is expected. If you expect more that 10000 records you can use the CSVReader.setMaxRowsInFile(int)

**Comment by hyddeepak** [comment]
Thanks for the updates. It helps.
