### ISSUE TITLE
Error "cannot find symbol" when using SDK generator

### ISSUE THREAD

**Issue by thobach** [forcedotcom/wsc#157]
Hi,
when I run:
$ java -classpath force-wsc-38.0.1-uber.jar com.sforce.ws.tools.wsdlc enterprise-developer.wsdl salesforce.jar

I get:
[WSC][wsdlc.main:71]Generating Java files from schema ...
[WSC][wsdlc.main:71]Generated 668 java files.
[WSC][wsdlc.main:71]Compiling to target 1.6... 
warning: [options] bootstrap class path not set in conjunction with -source 1.6
/var/folders/dg/511gn28s5wn6b3lpgsqkbc6w0000gn/T/wsc-scratch5483865119217326704tmp/com/sforce/soap/enterprise/sobject/SObject.java:116: error: cannot find symbol
      for (i = 0; i < MEMBER_NAMES.length; i++) {
           ^
  symbol:   variable i
  location: class SObject
/var/folders/dg/511gn28s5wn6b3lpgsqkbc6w0000gn/T/wsc-scratch5483865119217326704tmp/com/sforce/soap/enterprise/sobject/SObject.java:116: error: cannot find symbol
      for (i = 0; i < MEMBER_NAMES.length; i++) {
                  ^
  symbol:   variable i
  location: class SObject
[...]
  symbol:   variable i
  location: class Campaign
/var/folders/dg/511gn28s5wn6b3lpgsqkbc6w0000gn/T/wsc-scratch5483865119217326704tmp/com/sforce/soap/enterprise/sobject/Campaign.java:1948: error: cannot find symbol
           .append(com.sforce.ws.util.Verbose.toString(memberValues[i]))
                                                                    ^
  symbol:   variable i
  location: class Campaign
/var/folders/dg/511gn28s5wn6b3lpgsqkbc6w0000gn/T/wsc-scratch5483865119217326704tmp/com/sforce/soap/enterprise/sobject/Campaign.java:1946: error: cannot find symbol
           .append(MEMBER_NAMES[i])
                                ^
  symbol:   variable i
  location: class Campaign
100 errors
1 warning
Error: Failed to compile

I'm using OSX with Java 8.

Please advise.

**Comment by reubencornel** [comment]
Are you still seeing this problem?

**Comment by reubencornel** [comment]
Closed because I did not get a response.
