### ISSUE TITLE
NullPointerException in async communication

### ISSUE THREAD

**Issue by pavelsalamon** [forcedotcom/wsc#161]
Hi,
I sometimes get a NPE when asking for query result list. Here's the stacktrace:
java.lang.NullPointerException
    at com.sforce.async.BulkConnection.doHttpGet(BulkConnection.java:739)
    at com.sforce.async.BulkConnection.getBatchResultStream(BulkConnection.java:609)
    at com.sforce.async.BulkConnection.getQueryResultList(BulkConnection.java:639)
    at com.sforce.async.BulkConnection.getQueryResultList(BulkConnection.java:635)

The batch I'm asking for is in Completed state according to the status polling calls that I do before asking for results. I'm using WSC version 37.0.3.

From a quick look at the code it seems that the doHttpGet method in BulkConnection throws NPE when content-type header is missing.

If this can't be fixed directly, can the WSC report a nicer error?

Thanks!
Pavel

**Comment by egokt** [comment]
I created a new pull request for this.

If the pull request is accepted, it will take care of the case when NullPointerException is thrown. The error message will say "Server error returned in unknown format". Note that this error message can be less informative than desired: it also may mean that the server sent an empty response (i.e. connection timed out receiving the response). If the response is empty, then there is no content-type header, which is the case you observed from the code.
