### ISSUE TITLE
Issue with Auth Endpoint for Sandbox Users

### ISSUE THREAD

**Issue by prateekag** [forcedotcom/wsc#165]
Hi, I'm using soap calls to update records in salesforce organizations using a partner jar created by wsc. The problem I am facing is with the login call which throws the following error response when a sandbox user tries to login:
[[LoginFault [ApiFault exceptionCode='INVALID_LOGIN'
exceptionMessage='Invalid username, password, security token; or user locked out.'
extendedErrorDetails='{[0]}']]]
Please make a note that username, password and security token are all valid and user is not locked out.
On investigating further, I found out if I use "https://test.salesforce.com/services/Soap/u/37.0" as the auth endpoint instead of "https://login.salesforce.com/services/Soap/u/37.0", it works fine.
The issue is, there doesn't seem to be a common auth endpoint that works for all users.
Additional questions:
1. What is the difference between service endpoint and auth endpoint?
2. Which ones, out of the two endpoints - service and auth, do I need to set from my client code corresponding to the special cases like for the sandbox case that I mentioned above?
Right now, after figuring out the sandbox case, I have modified my code as follows:
String userSuppliedEndpoint ;//this is going to be user's server url
if (userSuppliedEndpoint != null){
      config.setServiceEndpoint(userSuppliedEndpoint);
      config.setAuthEndpoint(userSuppliedEndpoint);
}
But I don't know if this would fail in some cases or not. Looking to know if this is the correct way.
3. If a user has a custom instance, e.g. https://prateekagrawal-dev-ed.my.salesforce.com/services/Soap/u/7.0/00D28000001FJ73, then this custom instance should be set only as the service endpoint, or only as the auth endpoint, or both?

**Comment by reubencornel** [comment]
I believe you spoke to our product manager and he clarified this behavior.

So closing this issue.
