### ISSUE TITLE
java.util.Date is not translated into xsi:type="xsd:dateTime"

### ISSUE THREAD

**Issue by prateekag** [forcedotcom/wsc#167]
I have a Date/Time type field on Salesforce side which I am trying to update with a value from my java code like this:
SObject updatable= new SObject();
updatable.setType("MyCustomeObjectType");
updatable.setId("a0I2300000BbZ1S");
object.setField("Date", new java.util.Date()); // Step-A
connection.update(new SObject[]{updatable});

When I execute this, the element corresponding to Step-A in request xml looks like this:
<sobj:Date__c xsi:type="xsd:date">2016-10-10T04:35:30.000Z</Date__c>
Please make a note that the xsi:type is xsd:date and not xsd:dateTime which is not correct since a java.util.Date can represent a date/time instead, not just a date. Because of this bug, my dates are missing the time component in Salesforce organisation.

**Comment by reubencornel** [comment]
Java.util.Date should not map to Datetime because its not the right representation. Please use Calendar or GregorianCalendar if you want a date time mapping.

**Comment by prateekag** [comment]
Sorry, but I don't agree to this statement: "Java.util.Date should not map to Datetime because its not the right representation." java.util.Date represents a point in time. For the precise definition I would refer to java documentation, so here you go - https://docs.oracle.com/javase/7/docs/api/java/util/Date.html which says "The class Date represents a specific instant in time, with millisecond precision."
Hence it should map to datetime.

**Comment by reubencornel** [comment]
Almost all the methods on that class have been deprecated since JDK 1.1. In addition, that class has a bunch of problem around how it represents data, for instance it does not support locales correctly. If anything it only serves the purpose to hold a Date value.

If you do not agree with my thoughts feel free to fork wsc and customize it, thats why we provide you with the source code :) . You need to update the TypeMapper class.

**Comment by prateekag** [comment]
Ok, forking and customising makes sense and I accept that argument. But I have a disagreement on the first part of your reply. Deprecation of the Date class's methods has no binding to this bug. The reason is, Date class, even today, is how an instant in time is represented in java, e.g. if you have a Calendar object (let's call it calendar) and want to get the time instant from that object, you will do calendar.getTime() which will return a Date object (https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html#getTime()). No deprecated things have come into picture while doing this. So, it's really not about what's there inside the Date class, but just about what the Date class represents. Even in wsc, while generating the xml, the same thing would have been done, i.e. call calendar.getTime() to get the value.
