### ISSUE TITLE
The provided instructions result in a "class not found" exception

### ISSUE THREAD

**Issue by kpashov** [forcedotcom/wsc#172]
Since the classpath is specified directly in the cli in:

` java -classpath target/force-wsc-38.0.4-uber.jar com.sforce.ws.tools.wsdlc <inputwsdlfile> <outputjarfile>
`
It excludes the tools.jar, found in $JAVA_HOME/lib/tools.jar

To fix, I had to use:

`java -classpath "${JAVA_HOME}lib/tools.jar:<path to jar directory>/force-wsc-38.0.4-uber.jar" com.sforce.ws.tools.wsdlc <path to partner wsdl directory> <output directory>/partner.jar`

**Comment by reubencornel** [comment]
Documentation updated.
