### ISSUE TITLE
issue with generation of client- jar file is problamatic

### ISSUE THREAD

**Issue by surbhinanda** [forcedotcom/wsc#175]
trying to generate client jar file and when it is running  - it gave following errors

on force-wsc-39.0.0.jar: line 1: PK: command not found
/Users/surbhigupta/Desktop/salesforce_api/force-wsc-39.0.0.jar: line 3: ~?I: command not found
/Users/surbhigupta/Desktop/salesforce_api/force-wsc-39.0.0.jar: line 4: ?R?x??J3sJ??ťEI??%??]??l?z????PK: command not found
/Users/surbhigupta/Desktop/salesforce_api/force-wsc-39.0.0.jar: line 4:: command not found
/Users/surbhigupta/Desktop/salesforce_api/force-wsc-39.0.0.jar: line 5: ?}?Icom/PK: No such file or directory
/Users/surbhigupta/Desktop/salesforce_api/force-wsc-39.0.0.jar: line 6: ~?I
                                                                           com/sforce/PK: No such file or directory

**Comment by reubencornel** [comment]
Are you still seeing this issue?

**Comment by surbhinanda** [comment]
No
