### ISSUE TITLE
provide "uber" jar

### ISSUE THREAD

**Issue by imod** [forcedotcom/wsc#179]
In all your documentation you mention the use of the "uber"-jar - e.g.:

`java -jar target/force-wsc-39.0.1-uber.jar <inputwsdlfile> <outputjarfile>`

...but you don't provide it, instead I have to build wsc by myself to get it - or integrate the whole code generation into my maven build.

To make your documentation more consistent, you should provide the uber jar or adjust your documentation.

e.g. wrong docus are:

* https://github.com/forcedotcom/wsc
* https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_code_set_up_client.htm

**Comment by btajuddin-sfdc** [comment]
@imod We do provide the uber JAR. You can see it in the maven central repository here:

http://repo1.maven.org/maven2/com/force/api/force-wsc/39.0.1/

You do need to specify that you want the uber classifier when you configure the dependency, but you should be able to get it from maven without building from source.

**Comment by btajuddin-sfdc** [comment]
I do want to point out, though, that the executable JAR is extremely new (I made that change yesterday), and we haven't updated the maven repository yet. When we do, it will probably be version 39.0.2.

**Comment by imod** [comment]
@btajuddin-sfdc cool! a good additional help wold be if you just provide the two possible maven coordinates - at least in the README in your repo
