### ISSUE TITLE
Can not covert Bulk Query Result to XmlObject

### ISSUE THREAD

**Issue by kyleabcha** [forcedotcom/wsc#181]
Hi everyone,

I am trying to covert Bulk Query Result to XmlObject but it seemed to be not possible. Could anyone can help me in this.

**Test program:**

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;

import com.sforce.ws.bind.TypeInfo;
import com.sforce.ws.bind.TypeMapper;
import com.sforce.ws.bind.XmlObject;
import com.sforce.ws.parser.XmlInputStream;

public class TestBulkResult2XmlObject {
	public static void main(String[] args) throws Exception {
		InputStream in = new FileInputStream(new File("D:/bulkQueryResult.txt"));
		XmlInputStream xin = new XmlInputStream();
		xin.setInput(in, "UTF-8");
		xin.peekTag();
		if (xin.getEventType() == XmlInputStream.START_TAG) {
			TypeMapper typeMapper = new TypeMapper();
			TypeInfo info = new TypeInfo(xin.getNamespace(), xin.getName(), "http://www.w3.org/2001/XMLSchema", null, 1, 1, true);
			XmlObject obj = (XmlObject) typeMapper.readObject(xin, info, XmlObject.class);
			if (obj != null) {
				System.out.println("XML Object=" + obj.toString());
			}
		}
	}
}

**Content of bulkQueryResult.txt file:*

[bulkQueryResult.txt](https://github.com/forcedotcom/wsc/files/782380/bulkQueryResult.txt)

**Error message**

[errorMessage.txt](https://github.com/forcedotcom/wsc/files/782383/errorMessage.txt)

**Comment by reubencornel** [comment]
This is not a WSC problem.

The problem here is that you should have a "PartnerWsdl" jar somewhere in your class path. When we try to deserialize the object we try to deserialize it to the right type in this case we cannot find the sobject type.

**Comment by reubencornel** [comment]
Closed because of no response
