### ISSUE TITLE
BulkAPI implementation doesn't allow to retrieve fields longer than 32000

### ISSUE THREAD

**Issue by nzamosenchuk** [forcedotcom/wsc#182]
The length of the long text or rich text field is allowed to be up to 131072 characters long ( https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_customfields.htm ), but CSVReader contains a hardcoded field max size limit equals to 32000 (line 50)
```java
private int maxSizeOfIndividualCell = 32000;
```
(https://github.com/forcedotcom/wsc/blob/master/src/main/java/com/sforce/async/CSVReader.java).

Please set it to 131072  characters to properly support long text and rich text fields.

**Comment by metadaddy** [comment]
Hitting this with one of our users:

    com.sforce.async.CSVReader$CSVParseException: Exceeded max field size: 32581

Is it as simple as just changing the initialization of `maxSizeOfIndividualCell`?

**Comment by nzamosenchuk** [comment]
Yes. Looks like CSVReader class has been developed before SF introduced the large text fields. Simply changing the value of the constant and rebuilding the library brings the support for these large fields with BulkAPI.

**Comment by nzamosenchuk** [comment]
Hi @reubencornel , it would be really great if you could find some time to accept the pull request from @metadaddy, please. We're using exactly the same patch on our side for almost 3 months and the fix does work fine. 
Thank you in advance.

**Comment by nzamosenchuk** [comment]
Bump. Could it be merged and added to the next release, please?
Thanks in advance!

**Comment by reubencornel** [comment]
@abhinavChadda @cfineman-sfdc Please could you look at this?

**Comment by jarbaugh5** [comment]
Could @metadaddy 's PR please be reviewed and merged? Would be a big help when using this library

**Comment by catalandres** [comment]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/1649037/48029713-e3ae8780-e11c-11e8-8c63-af6afe7f7741.png">

...same here...

**Comment by jmdohn** [comment]
Ran into this as well.  This would be a greatly appreciated change!

**Comment by zerocool951** [comment]
Does anyone have there own version availible for quick download, that works with 131072 fied sizes ? 
Would be cool. thanks.
