### ISSUE TITLE
 BUILD FAILURE

### ISSUE THREAD

**Issue by zhouhu** [forcedotcom/wsc#193]
`mvn clean package

Results :

Tests in error:

Tests run: 29, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.219 s
[INFO] Finished at: 2017-05-12T13:40:04+08:00
[INFO] Final Memory: 26M/308M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.7.1:test (default-test) on project force-wsc: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\name\wsc\v40\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

**Comment by zhouhu** [comment]
java.nio.file.FileSystemException: C:\Users\name\AppData\Local\Temp\VoidReturnTest6835103972553301499\com\sforce\soap\docSample\SoapConnection.java: The process cannot access the file because it is being used by another process.

**Comment by zhouhu** [comment]
resolved by ignore maven test

adding following section to the pom.xml

` <plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-surefire-plugin</artifactId>
   <configuration>
     <testFailureIgnore>true</testFailureIgnore>
   </configuration>
 </plugin>`

**Comment by VenkateshSRajan** [comment]
thanks this worked for me too..
