### ISSUE TITLE
Error: Could not find or load main class com.sforce.ws.tools.wsdlc

### ISSUE THREAD

**Issue by sanam56** [forcedotcom/wsc#205]
Hi Team,

I am unable to run the command and I am receiving the following error

Error: Could not find or load main class com.sforce.ws.tools.wsdlc

**Comment by dgwgbh** [comment]
I am getting this same error as well.

**Comment by sanam56** [comment]
@dgwgbh : I am able to fix the issue now.

I placed all the jar files at one location. Below URL have detailed steps.

https://developer.salesforce.com/forums/?id=906F00000008zLZIAY
