### ISSUE TITLE
New JDKs without tools.jar

### ISSUE THREAD

**Issue by mplax7** [forcedotcom/wsc#222]
With JDK 9 and after, it appears as if there is no longer a tools.jar in the lib folder. Is there a way to install with these JDKs or do we have to use older versions?

**Comment by koenvi** [comment]
I'm an infrequent user of WSC.
I need to build a JAR for a new web service I'll be using, and stumbled into the same issue - the latest JDK's no longer have Tools.jar aboard.
How can we move forward without falling back to older (deprecated?) JDK versions?

**Comment by jluehe** [comment]
@mplax7 @koenvi, please note that JDK 8 is still being used at compile time, so tools.jar is still available for you to generate java stubs. tools.jar was only removed from the Java *runtime* version (JDK 9 and greater). The generated java stubs should not reference any symbols from tools.jar (tools.jar is only required to load the com.sun.tools.javac.Main class from it and invoke its "compile" method reflectively), and therefore, tools.jar should not be required at runtime. We are going to clarify the docs accordingly.
