### ISSUE TITLE
Support Java8 `java.time` package

### ISSUE THREAD

**Issue by khaledez** [forcedotcom/wsc#235]
Currently, `wsc` generates code for Java1.6 and uses `java.util.Calendar` for Salesforce `Date` fields.

Here is an example for creating a `Contact` in Java:
```java
java.util.Calendar birthDateCal = java.util.Calendar.getInstance();
birthDateCal.set(1980, 10, 06);

Contact contact = new Contact();
contact.setBirthdate(birthDateCal);
```

But Java 8 has become the most used version of Java, and it's becoming old (will not be supported after 2022).

I would like to be able to use `java.time` package for time-related objects, something like this:
```java
Contact contact = new Contact();
contact.setBirthdate(java.time.LocalDate.of(1980, 10, 06));
```
This would be a breaking change for the old code, so I suggest to create a new artifactId that compiles to Java 8 and uses `java.time` package. Maybe call it `force-wsc-java8`

**Comment by fancywriter** [comment]
@khaledez I have taken brief look inside :open_mouth: and found out few issues.
There are three XSD types of date and time https://www.w3schools.com/XML/schema_dtypes_date.asp :
 - **time**
 - **date**
 - **datetime**

They could (but don't have to!) have timezone info as a letter Z or offset (+01.00) at the end.
Also **time** and **datetime** could (but don't have to) have milliseconds at the end, no big issue here.

However, current implementation (back from old 2011...) which translates is to **java.util.Date**, **java.util.Calendar** and custom **Time**, which is again **java.util.Calendar**(surprise!) inside completely ignores this. But has very strange logic of parsing dates with era (`-` or `+` before the `yyyy-MM-dd`). Is it really used by SF? :open_mouth: 

https://github.com/forcedotcom/wsc/blob/30b7b0deb851bc80b33fc82d8614dfd615a669ec/src/main/java/com/sforce/ws/bind/DateCodec.java#L97

Of course I would kill it with fire :fire: and propose PR with changes to `java.time.*` classes with much simpler logic... I believe `DateTimeFormatter` could do 95% of the work (excluding few corner cases, may be it needs to support a couple of possible date formats than just one...). But can I?

What if this dates formats were implemented such way (out of standard) for a reason? Where can I find SF/SOAP documentation (or examples of payloads) with all possible date formats? Does it really have to support (what for?) dates before the Christian era? :church: 

@naaman @jesperfj @btajuddin-sfdc @ahalevy @sfdc-hhildebrand

**Comment by fancywriter** [comment]
Oh, actually there is one another stopper https://github.com/forcedotcom/wsc/blob/30b7b0deb851bc80b33fc82d8614dfd615a669ec/pom.xml#L155

Right now everything is compiled against java 7 (which is not supported after April 2015! https://java.com/en/download/faq/java_7.xml ), is it safe to upgrade to at least java 8?

**Comment by khaledez** [comment]
@fancywriter has provided a solution in PR #247 .
By default, `java.time` objects are not used.

You need to provide a system property to enable them, for example:
```bash
java -jar target/force-wsc-$VERSION-uber.jar -P"java-time"=true <inputwsdlfile> <outputjarfile>
```

**Comment by liff** [comment]
Are you planning to publish force-*-api artifacts (#82) with java.time support enabled?
