### ISSUE TITLE
jackson-mapper-asl is vulnerable

### ISSUE THREAD

**Issue by lokendra2211** [forcedotcom/wsc#252]
hi team 
we are using force-Wsc.48  which is having dependency in jackson-mapper-asl 1.9.13 and our security team found that jackson-mapper-asl is vulnerable. so can you please update this dependency with jackson-databind 2.10.1.
NOTE:please find the  attached 
[DetailedReport_Connectors_20_Jan_2020.pdf](https://github.com/forcedotcom/wsc/files/4085930/DetailedReport_Connectors_20_Jan_2020.pdf)
report for the jackson-mapper-asl jar

thanks and regards
Lokendra

**Comment by mbenoit99** [comment]
+1 for fixing this.
https://snyk.io/vuln/SNYK-JAVA-ORGCODEHAUSJACKSON-534878

**Comment by jyothsna-smax** [comment]
Any update on this?

**Comment by mgrumbach** [comment]
Fix has been published in WSC 49.2.0.
