### ISSUE TITLE
com.sforce.ws.ConnectionException: Unexpected element. Parser was expecting element 'urn:partner.soap.sforce.com:currencySymbol' but found 'urn:partner.soap.sforce.com:chatterExternal'

### ISSUE THREAD

**Issue by jhabarunk** [forcedotcom/wsc#279]
After updating force-wsc  version to 49.0.0, facing below issue:
com.sforce.ws.ConnectionException: Unexpected element. Parser was expecting element 'urn:partner.soap.sforce.com:currencySymbol' but found 'urn:partner.soap.sforce.com:chatterExternal'

Can some one please help me on this?

**Comment by jhabarunk** [comment]
There were dependencies conflict.

**Comment by chaxxxxxjxx** [comment]
@jhabarunk I am experiencing the same issue, what did you do to resolve it? Thanks

**Comment by jhabarunk** [comment]
It was a dependency issue. While creating fat jar two versions of the same force dependencies were being added. Fixed the same and it worked
