### ISSUE TITLE
Why is the Force Tooling API not maintained in MvnRepository?

### ISSUE THREAD

**Issue by Shadow-Devil** [forcedotcom/wsc#308]
Today I saw, that most of the Jars are maintained inside maven central: https://mvnrepository.com/artifact/com.force.api
All partner, metadata and apex APIs are well maintained, but the tooling API was last updated in 2015 with version 32.0. 
It is also located at https://repo.spring.io/plugins-release/ where I get an 401 Unauthorized response.
Is nobody using the tooling API or is everybody generating it by themselves?
 
I would really appreciate if this would also be added to maven central, so everybody can use the generated jar and don't have to generate it.

**Comment by ttomaszewski** [comment]
+1
We're now seeing that we need to generate a new JAR to be compatible with the latest Metadata WSDL....this is a huge pain and shouldn't be necessary...

**Comment by nehaahlawat** [comment]
@Shadow-Devil 
The Tooling JAR generated in version 32.0 is deprecated and is not maintained. To generate it yourself, follow [these instructions](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_quickstart_steps.htm) and substitute the Tooling WSDL for the Enterprise WSDL throughout.
