### ISSUE TITLE
Date serialization issue

### ISSUE THREAD

**Issue by gitfish** [forcedotcom/wsc#40]
There appears to be a fairly significant date serialization issue in the codebase:

Date fields are currently getting generated as a field of type Calendar. When the field is serialized, the schema type information is ignored and the CalendarCodec is simply used to produce the date value is yyyy-MM-dd'T'HH:mm:ss blah format. As the calendar is being adjusted for GMT, the day portion of the calendar may be reduced by a day. As Salesforce ignores the time portion for date fields, we end up with a date that is reduced by a day.
The offending code is at com.sforce.ws.bind.TypeMapper.writeSingleObject (line 357):

else if (value instanceof Calendar || value instanceof Date) {
            String s = calendarCodec.getValueAsString(value);
            writeSimpleType(out, info, s, true, Calendar.class.getName());
        }

**Comment by nrodrigues** [comment]
PR #90 has a fix for this issue, voting for it would be helpful

**Comment by reubencornel** [comment]
Closed because PR has been merged.
