### ISSUE TITLE
No BigDecimal support in sforce jar libray

### ISSUE THREAD

**Issue by mcoaker** [forcedotcom/wsc#57]
The TypeMapper class (com.sforce.ws.bind.TypeMapper.class) doesn't support the BigDecimal to Decimal conversion.
Although SF doesn't handle numeric fields larger than 18 digits, there is a loss of precision for large numbers when handling them as doubles that is affecting imports and exports to SF when using this library. We have seen this issue around a numeric field that represents currency where a loss of precision is not acceptable.

Is there any other way to support BigDecimals?

**Comment by reubencornel** [comment]
We have a feature for the soap api which is behind a perm that would let you use big decimal objects. Please get in touch with Jay Hurst to turn this feature on for you. That said, this feature is still pilot.

The following pull request supports big decimal in WSC
https://github.com/forcedotcom/wsc/pull/128
