### ISSUE TITLE
mvn test exception

### ISSUE THREAD

**Issue by javen-hao** [forcedotcom/wsc#76]
when Run "mvn clean package -Dgpg.skip" in windows command.

error following :

Failed tests:
  testGenerateSObjectSource(com.sforce.ws.codegen.SObjectCodeGeneratorTest)

Tests run: 15, Failures: 6, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.316 s
[INFO] Finished at: 2014-10-11T17:01:06+08:00
[INFO] Final Memory: 24M/299M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.7.1:test (default-test) on project force-wsc: There are test failures.
[ERROR]
[ERROR] Please refer to D:\wsc\wsc\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by ozgit** [comment]
I am getting error when trying to do mvn clean package.  I am using Windows 7 and JKD version 1.7.0_79. Can someone please help.

Error message:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.sforce.async.CSVReaderTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.364 sec
Running com.sforce.ws.bind.XmlObjectTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.225 sec
Running com.sforce.ws.codegen.AggregateCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.461 sec <<< FA
ILURE!
Running com.sforce.ws.codegen.ComplexTypeCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.206 sec <<< FA
ILURE!
Running com.sforce.ws.codegen.ConnectionCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.258 sec <<< FA
ILURE!
Running com.sforce.ws.codegen.ConnectorCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.16 sec <<< FAI
LURE!
Running com.sforce.ws.codegen.SimpleTypeCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.197 sec <<< FA
ILURE!
Running com.sforce.ws.codegen.SObjectCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.16 sec <<< FAI
LURE!

Results :

Failed tests:
  testGenerateSObjectSource(com.sforce.ws.codegen.SObjectCodeGeneratorTest)

Tests run: 16, Failures: 6, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31.989 s
[INFO] Finished at: 2015-12-14T10:56:30-05:00
[INFO] Final Memory: 19M/125M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
7.1:test (default-test) on project force-wsc: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Project\HCL-OCD\SFDC_project\JAVA\WSDL_SFDC\wsc-maste
r\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by ozgit** [comment]
Below is complete log of command "mvn clean package". Can someone please help me ASAP.

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building force-wsc 36.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ force-wsc ---
[INFO] Deleting C:\Project\HCL-OCD\SFDC_project\JAVA\WSDL_SFDC\wsc-master\target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ force-wsc ---
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ force-wsc ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 20 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ force-wsc ---
[INFO] Compiling 119 source files to C:\Project\HCL-OCD\SFDC_project\JAVA\WSDL_SFDC\wsc-master\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:testResources (default-testResources) @ force-wsc ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ force-wsc ---
[INFO] Compiling 9 source files to C:\Project\HCL-OCD\SFDC_project\JAVA\WSDL_SFDC\wsc-master\target\test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.7.1:test (default-test) @ force-wsc ---
[INFO] Surefire report directory: C:\Project\HCL-OCD\SFDC_project\JAVA\WSDL_SFDC\wsc-master\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.sforce.async.CSVReaderTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.245 sec
Running com.sforce.ws.bind.XmlObjectTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.069 sec
Running com.sforce.ws.codegen.AggregateCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.195 sec <<< FAILURE!
Running com.sforce.ws.codegen.ComplexTypeCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.192 sec <<< FAILURE!
Running com.sforce.ws.codegen.ConnectionCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.194 sec <<< FAILURE!
Running com.sforce.ws.codegen.ConnectorCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.148 sec <<< FAILURE!
Running com.sforce.ws.codegen.SimpleTypeCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.154 sec <<< FAILURE!
Running com.sforce.ws.codegen.SObjectCodeGeneratorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.163 sec <<< FAILURE!

Results :

Failed tests: 
  testGenerateSObjectSource(com.sforce.ws.codegen.SObjectCodeGeneratorTest)

Tests run: 16, Failures: 6, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.819 s
[INFO] Finished at: 2015-12-14T11:23:26-05:00
[INFO] Final Memory: 21M/242M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.7.1:test (default-test) on project force-wsc: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Project\HCL-OCD\SFDC_project\JAVA\WSDL_SFDC\wsc-master\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by gnguyen-sfdc** [comment]
The tests are likely failing due to line breaks on Windows vs Unix. There haven't been any fixes for that yet. You can use -DskipTests to skip the tests, e.g. "mvn clean package -DskipTests".

**Comment by ozgit** [comment]
I understand. Thank you. 
I tried "mvn clean package -DskipTests". Windows Command shell prompted me for GPG passphrase. Should I enter some dummy characters as part of this passphrase? I see there is option -Dgpg.skip to skip gpgsign. But I am not sure if I can use both -DskipTests and -Dgpg.skip together. Can I use both options together?

**Comment by gnguyen-sfdc** [comment]
Yes, both can be used together.

**Comment by ozgit** [comment]
Thank you gnguyen-sfdc for your help. I used both options and .jar files have been generated.

I ran into a new stack of errors when generating .jar using wsdl.xml file. I am googling now to understand resolutions. I appreciate if you have workaround for this. If not I will continue my research on google. Thank you again for your help.

[WSC][wsdlc.main:71]Generating Java files from schema ...
[WSC][wsdlc.main:71]Generated 843 java files.
java.io.FileNotFoundException: C:\Program Files\Java\jre7\lib\tools.jar (The sys
tem cannot find the file specified)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at com.sforce.ws.codegen.ToolsJarClassLoader.<init>(ToolsJarClassLoader.
java:52)
        at com.sforce.ws.codegen.Compiler.findCompilerInToolsJar(Compiler.java:6
9)
        at com.sforce.ws.codegen.Compiler.<init>(Compiler.java:57)
        at com.sforce.ws.codegen.Generator.compileTypes(Generator.java:133)
        at com.sforce.ws.tools.wsdlc.run(wsdlc.java:117)
        at com.sforce.ws.tools.wsdlc.run(wsdlc.java:149)
        at com.sforce.ws.tools.wsdlc.main(wsdlc.java:71)
Error: Unable to find compiler. Make sure that tools.jar is in your classpath: j
ava.io.FileNotFoundException: C:\Program Files\Java\jre7\lib\tools.jar (The syst
em cannot find the file specified)

**Comment by ozgit** [comment]
Please ignore my previous comment. I copied tools.jar file from JDK to JRE folder on my system and that resolved issue.
