### ISSUE TITLE
Missing import packages com.sforce.soap.*

### ISSUE THREAD

**Issue by raghumark123** [forcedotcom/wsc#77]
Hi
When I build the package I see that the above are missing. As a result my code fails to compile.
Here is the code header that is causing the failure. Any help would be appreciated.

Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
    EnterpriseConnection cannot be resolved to a type
    Connector cannot be resolved

```
at Main.main(Main.java:30)
```

import com.sforce.soap.enterprise.Connector;
import com.sforce.soap.enterprise.DeleteResult;
import com.sforce.soap.enterprise.EnterpriseConnection;
import com.sforce.soap.enterprise.Error;
import com.sforce.soap.enterprise.QueryResult;
import com.sforce.soap.enterprise.SaveResult;
import com.sforce.soap.enterprise.sobject.Account;
import com.sforce.soap.enterprise.sobject.Contact;

**Comment by reubencornel** [comment]
EnterpriseConnection is a class that is generated from your wsdl. It is not provided as a part of wsc. Please make sure you have the jar generated from the wsdl in your class path.
