### ISSUE TITLE
Windows -- tools trying to use wrong path for Java

### ISSUE THREAD

**Issue by TaDaa** [forcedotcom/wsc#81]
All of my user and system paths are pointed to JDK7.  JAVA_HOME is pointed to JDK7.  

Java -version shows JDK7

When I attempt to compile a wsdl, an exception occurs:
FileNotFoundException: ....jre7\lib\tools.jar (clearly the wrong directory)

**Comment by reubencornel** [comment]
Not much we can do about tools.jar not being found.
