### ISSUE TITLE
Cannot Create .jar Files

### ISSUE THREAD

**Issue by rdgoldber** [forcedotcom/wsc#92]
I have been trying to generate .jar files for the last 3 days, and have been unsuccessful.

Here are the data files I have, in this folder:
C:\Robert_Data\SF.com Development\
- enterprise.wsdl
- metadata.wsdl
- partner.wsdl
- force-wsc-33.0.3.jar

I have been trying to run this: "java -classpath ./wsc-33.0.3.jar com.sforce.ws.tools.wsdlc enterprise.wsdl enterprise.jar"

and have consistently gotten this error:

Error: Could not find or load main class com.sforce.ws.tools.wsdlc

Can anyone help, please?

**Comment by gnguyen-sfdc** [comment]
Hi,
From where did you get the force-wsc-33.0.3.jar? Also, can you open the jar file and verify you can find the wsdlc class in com/sforce/ws/tools ?

**Comment by rdgoldber** [comment]
I downloaded that file from here: h
![class](https://cloud.githubusercontent.com/assets/11560965/6756568/2498e894-cf01-11e4-9d99-ab7aaf01d8c7.jpg)
ttp://central.maven.org/maven2/com/force/api/force-wsc/33.0.3/force-wsc-33.0.3.jar

Yes - it's here.

**Comment by gnguyen-sfdc** [comment]
Instead of using the force-wsc-33.0.3.jar, can you use the force-wsc-33.0.3-uber.jar ?

**Comment by rdgoldber** [comment]
force-wsc-33.0.3-uber.jar was blank, so I went with force-wsc-33.0.2-uber.jar.  Same error.
See image:

![nw](https://cloud.githubusercontent.com/assets/11560965/6757446/849a185c-cf07-11e4-9b5e-ac0506a9d7cc.jpg)

**Comment by gnguyen-sfdc** [comment]
In the first instance, with 33.0.3.jar, could you do "java -classpath force-wsc-33.0.3.jar com.sforce.ws.tools.wsdlc enterprise.wsdl enterprise.jar" ? You may be missing that the jars are "force-wsc-33.0.3.jar", not "wsc-33.0.3.jar".

**Comment by rdgoldber** [comment]
Okay - now I'm getting this error:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFWKeyCallback
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
    at java.lang.Class.privateGetMethodRecursive(Unknown Source)
    at java.lang.Class.getMethod0(Unknown Source)
    at java.lang.Class.getMethod(Unknown Source)
    at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
    at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.glfw.GLFWKeyCallback
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 7 more

**Comment by thanneru** [comment]
It seems like you may be missing some dependent jar files. Specifically, the StringTemplate library from http://www.stringtemplate.org/

Can you download that library, and include it in your class path? So, something like below (just make sure to replace x,y,z with your jar file names):
java -classpath C:\force-wsc-x.y.z.jar;C:\ST-x.y.z.jar com.sforce.ws.tools.wsdlc enterprise.wsdl enterprise.jar

**Comment by gnguyen-sfdc** [comment]
That is correct. If you use the uber jar, the dependencies will be taken care for you (they are included inside). Unfortunately, the 33.0.3 uber jar is empty, something I didn't know about until now. You can either gather the dependencies yourself, like thanneru suggested, or wait until the next version of the artifact is released, where the uber jar should be fixed.

**Comment by rdgoldber** [comment]
I had to copy over the tools.jar file - wasn't appearing in the correct area, but this is finally done.  Nearly 3 full days of this, and finally all set.  Thanks - both of you for your help!
