### ISSUE TITLE
when running command I get error 

### ISSUE THREAD

**Issue by hitesh-patel-ef** [forcedotcom/wsc#94]
When running command follwing to generate Jar file  I am getting error 

java -classpath wsc-34.jar c:\Users\hitesh.patel\Documents\wsc-master\wsc\src\main\java\com\sforce\ws\tools.wsdlc ewsdl.wsdl ejar.jar

also 

who do i execute following 

git clone https://github.com/forcedotcom/wsc.git
mvn clean package

 To skip the gpg signing, run the following command
mvn clean package -Dgpg.skip

**Comment by hitesh-patel-ef** [comment]
When running command follwing to generate Jar file I am getting error 

java -classpath wsc-34.jar c:\Users\hitesh.patel\Documents\wsc-master\wsc\src\main\java\com\sforce\ws\tools.wsdlc ewsdl.wsdl ejar.jar

also 

who do i execute following 

git clone https://github.com/forcedotcom/wsc.git
 mvn clean package

To skip the gpg signing, run the following command
 mvn clean package -Dgpg.skip

**Comment by guanzhijie** [comment]
Can you describe what error you got for generating the jar files on tooling.wsdl?
